name: Sample

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-one:
    runs-on: ubuntu-latest
    steps:
      - name: build one
        run: echo "build one"
  
  build-two:
    needs: ["build-one"]
    runs-on: ubuntu-latest
    steps:
      - name: build two
        run: env
  
  build-three:
    runs-on: ubuntu-latest
    steps:
      - name: build three
        run: echo ${{ secrets.TestSecret }}
  
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: echo "Test File" > file.text
      - uses: actions/upload-artifact@v3
        with:
          name: file
          path: file.txt
